config/routes.rb
Rails.application.routes.draw do
  resources :critics
  resources :games
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :games
end

app/models/critic.rb
class Critic < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :company
  has_many :critics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :start_date, :country)
    end
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController
  before_action :set_critic, only: [:show, :edit, :update, :destroy]

  # GET /critics
  # GET /critics.json
  def index
    @critics = Critic.all
  end

  # GET /critics/1
  # GET /critics/1.json
  def show
  end

  # GET /critics/new
  def new
    @critic = Critic.new
  end

  # GET /critics/1/edit
  def edit
  end

  # POST /critics
  # POST /critics.json
  def create
    @critic = Critic.new(critic_params)

    respond_to do |format|
      if @critic.save
        format.html { redirect_to @critic, notice: 'Critic was successfully created.' }
        format.json { render :show, status: :created, location: @critic }
      else
        format.html { render :new }
        format.json { render json: @critic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /critics/1
  # PATCH/PUT /critics/1.json
  def update
    respond_to do |format|
      if @critic.update(critic_params)
        format.html { redirect_to @critic, notice: 'Critic was successfully updated.' }
        format.json { render :show, status: :ok, location: @critic }
      else
        format.html { render :edit }
        format.json { render json: @critic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /critics/1
  # DELETE /critics/1.json
  def destroy
    @critic.destroy
    respond_to do |format|
      format.html { redirect_to critics_url, notice: 'Critic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_critic
      @critic = Critic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def critic_params
      params.require(:critic).permit(:username, :title, :body, :game_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :description, :price, :release_date, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= company.start_date %></td>
        <td><%= company.country %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @company.start_date %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> | <%= link_to 'Back',
companies_path %>

<h3>Games</h3>

<ul>
  <% @company.games.each do |game| %>
  <li>
    <a href="<%= "/games/#{game.id}"  %> "><strong> <%= game.name%> </strong></a>
    <p><%= game.description%></p>
    <p><small>price: $ <%= game.price%> </small></p>
  </li>
  <% end %>
</ul>

app/views/critics/_form.html.erb
<%= form_with(model: critic, local: true) do |form| %>
  <% if critic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(critic.errors.count, "error") %> prohibited this critic from being saved:</h2>

      <ul>
        <% critic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.text_field :game_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/critics/edit.html.erb
<h1>Editing Critic</h1>

<%= render 'form', critic: @critic %>

<%= link_to 'Show', @critic %> |
<%= link_to 'Back', critics_path %>

app/views/critics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Critics</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Title</th>
      <th>Body</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @critics.each do |critic| %>
      <tr>
        <td><%= critic.username %></td>
        <td><%= critic.title %></td>
        <td><%= critic.body %></td>
        <td><%= critic.game_id %></td>
        <td><%= link_to 'Show', critic %></td>
        <td><%= link_to 'Edit', edit_critic_path(critic) %></td>
        <td><%= link_to 'Destroy', critic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Critic', new_critic_path %>

app/views/critics/new.html.erb
<h1>New Critic</h1>

<%= render 'form', critic: @critic %>

<%= link_to 'Back', critics_path %>

app/views/critics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @critic.username %>
</p>

<p>
  <strong>Title:</strong>
  <%= @critic.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @critic.body %>
</p>

<p>
  <strong>Game:</strong>
  <%= @critic.game.name %>
</p>

<%= link_to 'Edit', edit_critic_path(@critic) %> |
<%= link_to 'Back', critics_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Release date</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= game.price %></td>
        <td><%= game.release_date %></td>
        <td><%= game.company_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @game.release_date %>
</p>

<p>
  <strong>Company:</strong>
  <a href="<%= "/companies/#{@game.company_id}" %>"><%= @game.company.name %></a>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

<h3>Critics</h3>

<ul>
  <% @game.critics.each do |critic| %>
  <li>
    <strong><%= critic.username %> </strong>
    <p><%= critic.title%> </p>
    <p><small><%= critic.body%> </small></p>
  </li>
  <% end %>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Criticx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>